### ISSUE TITLE
thanks for making the tufte css sidenote markdown extension

### ISSUE THREAD

**Issue by ttrefren** [andrewstephens75/gensite#6]
I was inspired by yours & wrote one using the same syntax, but supporting multiple paragraphs in a side/margin note: https://github.com/ttrefren/tufte-css-markdown-python

just thought you might be interested!

cheers,
Tim

**Comment by andrewstephens75** [comment]
Thank you for your kind comments. One flaw in my system is that it doesn't handle nested markdown well at all, your use of a proper ]<- end delimiter gets around that problem neatly, I think.
